const tg=window.Telegram?.WebApp;if(tg){tg.expand();tg.ready();tg.setHeaderColor?.('#0f172a');tg.setBackgroundColor?.('#08111f');}
const CONFIG={API_URL:'',USE_MOCK:true};
const mockData={profile:{weight:72.4,height:176,age:29,sex:'Мужской',activity:'Средняя',goal:'Похудение',targetCalories:1933,maintainCalories:2274,proteinTarget:116},today:{calories:1385,target:1933,protein:88,fat:46,carbs:149,weight:72.4,weightDelta:-0.3,recommendation:'Сегодня ты держишь хороший темп. По калориям запас ещё есть, но белок можно чуть усилить: подойдут яйца, курица, творог или рыба.',meals:[{name:'Овсянка с бананом',sub:'350 ккал • Б 11 / Ж 6 / У 62'},{name:'Курица с рисом',sub:'520 ккал • Б 38 / Ж 12 / У 61'},{name:'Йогурт и яблоко',sub:'190 ккал • Б 9 / Ж 4 / У 27'},{name:'Кофе с молоком',sub:'75 ккал • Б 2 / Ж 2 / У 10'},{name:'Орехи',sub:'250 ккал • Б 8 / Ж 22 / У 9'}]},week:{days:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],calories:[1820,1710,2040,1930,1670,2110,1385],weight:[73.0,72.9,72.8,72.7,72.6,72.7,72.4]}};
let charts={},lastMealResult=null;
function getUserLabel(){const u=tg?.initDataUnsafe?.user;if(!u)return 'demo mode';return u.first_name?`@${u.first_name}`:'telegram user'}
function percent(a,b){if(!b)return 0;return Math.max(0,Math.min(100,Math.round(a/b*100)))}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v}
function formatDelta(v){const n=Number(v||0);const s=n>0?'+':'';return `${s}${n.toFixed(1)} кг`}
function updateMacroBar(id,v,g){const p=percent(v,g);const e=document.getElementById(id);if(e)e.style.width=`${p}%`}
function renderProfile(p){const root=document.getElementById('profileGrid');const items=[['Вес',`${p.weight} кг`],['Рост',`${p.height} см`],['Возраст',`${p.age}`],['Пол',p.sex],['Активность',p.activity],['Цель',p.goal],['Поддержание',`${p.maintainCalories} ккал`],['Цель на день',`${p.targetCalories} ккал`],['Белок',`${p.proteinTarget} г`]];root.innerHTML=items.map(([l,v])=>`<div class="profile-item"><div class="label">${l}</div><div class="value">${v}</div></div>`).join('')}
function renderToday(t,p){setText('caloriesValue',t.calories);setText('targetValue',t.target);setText('weightValue',t.weight.toFixed(1));setText('weightDeltaText',`Изменение ${formatDelta(t.weightDelta)}`);setText('remainText',`Осталось ${Math.max(0,t.target-t.calories)} ккал`);setText('proteinValue',`${t.protein} г`);setText('fatValue',`${t.fat} г`);setText('carbsValue',`${t.carbs} г`);updateMacroBar('proteinBar',t.protein,p.proteinTarget);updateMacroBar('fatBar',t.fat,Math.round(p.targetCalories*.35/9));updateMacroBar('carbsBar',t.carbs,Math.round(p.targetCalories*.45/4));document.getElementById('todayList').innerHTML=t.meals.map(m=>`<div class="meal-item"><div class="meal-top"><div class="meal-name">${m.name}</div></div><div class="meal-sub">${m.sub}</div></div>`).join('');document.getElementById('recommendationText').textContent=t.recommendation;renderRing(t.calories,t.target)}
function renderRing(v,t){const ctx=document.getElementById('calorieRing');if(charts.ring)charts.ring.destroy();const p=percent(v,t);setText('ringPercent',`${p}%`);charts.ring=new Chart(ctx,{type:'doughnut',data:{labels:['Использовано','Осталось'],datasets:[{data:[v,Math.max(0,t-v)],backgroundColor:['#f4c86a','rgba(255,255,255,.08)'],borderWidth:0,cutout:'78%'}]},options:{responsive:true,plugins:{legend:{display:false},tooltip:{enabled:false}}}})}
function renderWeek(w){const c=document.getElementById('weekCaloriesChart'),wt=document.getElementById('weekWeightChart');if(charts.calories)charts.calories.destroy();if(charts.weight)charts.weight.destroy();charts.calories=new Chart(c,{type:'bar',data:{labels:w.days,datasets:[{label:'Калории',data:w.calories,borderRadius:12,backgroundColor:'#f4c86a'}]},options:{maintainAspectRatio:false,scales:{x:{ticks:{color:'#9fb2cc'},grid:{display:false}},y:{ticks:{color:'#9fb2cc'},grid:{color:'rgba(255,255,255,.06)'}}},plugins:{legend:{display:false}}}});charts.weight=new Chart(wt,{type:'line',data:{labels:w.days,datasets:[{label:'Вес',data:w.weight,tension:.35,fill:true,borderColor:'#f4c86a',backgroundColor:'rgba(244,200,106,.12)',pointRadius:4,pointBackgroundColor:'#f4c86a'}]},options:{maintainAspectRatio:false,scales:{x:{ticks:{color:'#9fb2cc'},grid:{display:false}},y:{ticks:{color:'#9fb2cc'},grid:{color:'rgba(255,255,255,.06)'}}},plugins:{legend:{display:false}}}})}
async function api(action,payload={}){const user=tg?.initDataUnsafe?.user||{id:'demo-user'};if(CONFIG.USE_MOCK||!CONFIG.API_URL){if(action==='dashboard')return structuredClone(mockData);if(action==='analyze_food'){const text=String(payload.text||'').trim();return{ok:true,body:`Похоже на <span class="accent">${text}</span>.<br><br>🔥 Калории: <span class="accent">620 ккал</span><br>🥩 Белки: <span class="accent">28 г</span><br>🥑 Жиры: <span class="accent">21 г</span><br>🍞 Углеводы: <span class="accent">72 г</span><br><br>Запись сохранить в дневник?`}}if(action==='save_food')return{ok:true};if(action==='update_weight')return{ok:true,newWeight:payload.weight,delta:-0.3};if(action==='profile_analysis')return{ok:true,text:'Сейчас тебе логичнее держаться мягкого дефицита. Вес идёт вниз спокойно, темп хороший. Не режь калории слишком сильно: держи фокус на белке и регулярности.'};return{ok:true}}const res=await fetch(CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,user_id:user.id,initData:tg?.initData||'',...payload})});return res.json()}
async function loadDashboard(){document.getElementById('userBadge').textContent=getUserLabel();const data=await api('dashboard');renderProfile(data.profile);renderToday(data.today,data.profile);renderWeek(data.week)}
function showDialog(id){document.getElementById(id)?.showModal()} function closeDialog(id){document.getElementById(id)?.close()}
async function analyzeFood(){const text=document.getElementById('foodInput').value.trim();if(!text)return;const res=await api('analyze_food',{text});lastMealResult={text};document.getElementById('resultBody').innerHTML=res.body||'Не удалось получить расчёт.';closeDialog('foodDialog');showDialog('resultDialog')}
async function saveFood(){if(!lastMealResult)return;await api('save_food',lastMealResult);closeDialog('resultDialog');document.getElementById('foodInput').value='';await loadDashboard();tg?.showPopup?.({title:'Готово',message:'Запись добавлена в дневник ✅',buttons:[{type:'ok'}]})}
async function saveWeight(){const raw=document.getElementById('weightInput').value;const weight=Number(raw);if(!weight)return;await api('update_weight',{weight});closeDialog('weightDialog');await loadDashboard();tg?.showPopup?.({title:'Вес обновлён',message:`${weight.toFixed(1)} кг сохранено`,buttons:[{type:'ok'}]})}
async function profileAnalysis(){const res=await api('profile_analysis');document.getElementById('recommendationText').textContent=res.text||'Анализ временно недоступен.'}
function initNav(){document.querySelectorAll('.nav-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const s=btn.dataset.screen;if(s==='day')document.getElementById('todayList')?.scrollIntoView({behavior:'smooth',block:'start'});else if(s==='week')document.getElementById('weekCaloriesChart')?.scrollIntoView({behavior:'smooth',block:'start'});else if(s==='profile')document.getElementById('profileGrid')?.scrollIntoView({behavior:'smooth',block:'start'});else window.scrollTo({top:0,behavior:'smooth'})})})}
document.getElementById('addFoodBtn').addEventListener('click',()=>showDialog('foodDialog'));document.getElementById('updateWeightBtn').addEventListener('click',()=>showDialog('weightDialog'));document.getElementById('submitFoodBtn').addEventListener('click',e=>{e.preventDefault();analyzeFood()});document.getElementById('saveMealBtn').addEventListener('click',e=>{e.preventDefault();saveFood()});document.getElementById('submitWeightBtn').addEventListener('click',e=>{e.preventDefault();saveWeight()});document.getElementById('analysisBtn').addEventListener('click',profileAnalysis);document.getElementById('refreshDayBtn').addEventListener('click',loadDashboard);document.getElementById('syncBtn').addEventListener('click',loadDashboard);document.getElementById('openPhotoBtn').addEventListener('click',()=>tg?.showAlert?.('Фото-режим подключается через твой backend/n8n. Сейчас это демонстрационный экран.'));document.getElementById('editProfileBtn').addEventListener('click',()=>tg?.showAlert?.('Редактирование профиля лучше вынести в отдельный экран mini app или оставить в боте.'));document.getElementById('proBtn').addEventListener('click',()=>tg?.showAlert?.('Здесь можно открыть экран подписки PRO или внешнюю оплату.'));
window.addEventListener('load',async()=>{initNav();if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./service-worker.js')}catch(e){}}loadDashboard()});